### ISSUE TITLE
`build-public` shouldn't require a schema

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#153]
The *build-public* command requires a `schema-path` option to be provided. The schema serves to identify components that should be deleted. 

This should be made optional. There is the realistic use-case that someone would only want to delete properties in the `internal` namespace without deleting any components.

**Comment by italvi** [comment]
Agree, as this way we would just fulfill the [property taxonomy](https://github.com/CycloneDX/cyclonedx-property-taxonomy?tab=readme-ov-file#registered-top-level-namespaces) of cdx.
