### ISSUE TITLE
Should `amend` set `compositions` to `unknown` rather than `incomplete`?

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#161]
As of now, the _amend_ command creates a `compositions` entry with `.aggregate == "incomplete"`. 

The stated goal of this is to explicitly disclaim any completeness of the provided information in the interest of revealing known unknowns. Shouldn't the value then not rather be `unknown`, which expresses exactly that? "Incomplete" means: _this SBOM **is known to be** incomplete_, which it might not actually be. "Unknown" only says: _we don't guarantee completeness_, which seems to be exactly our intent.

**Comment by italvi** [comment]
Agree, however, I would like to debate about not adding the `bom.metadata.component` to the list, as we should at least state that we know our top-level dependencies. Your opinion?

**Comment by mmarseu** [comment]
@italvi Seems reasonable to me. 
In any case, this feature is a result of internal requirements and you're the person to set those requirements. So I don't get a say 😉
