### ISSUE TITLE
Missing attribution for license data

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#164]
Ah, irony is beautiful 😆 

There we went and _copied raw data about licenses_ from other open-source projects and neglected to make sure we follow their license conditions.

`cdxev/amend/license_name_spdx_id_map.json` is largely based off of https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/resources/license-mapping.json which is [licensed under Apache-2.0](https://github.com/CycloneDX/cyclonedx-core-java/?tab=readme-ov-file#copyright--license).

We also incorporated additional license names and ids from [SPDX](https://spdx.org/licenses/). Since the [raw data](https://github.com/spdx/license-list-XML) that the site is based on - equally ironically - doesn't specify a license, I'd say we refer to the license of the website which is copyrighted by The Linux Foundation and under [CC-BY-3.0](https://creativecommons.org/licenses/by/3.0/).

**Comment by italvi** [comment]
Should we really use CC here? Though it is compatible with all versions of GPL, according to [gnu](https://www.gnu.org/licenses/license-list.en.html#ccby) it should not be used for software.

**Comment by mmarseu** [comment]
I've added a NOTICE file to #144 which hopefully should fulfil our obligations resulting from the Apache-2.0 license and CC-BY-3.0.
I was too lazy to create a separate PR for this, although that could definitely be done, if #144 will take too long to merge.
