### ISSUE TITLE
Ad further options for the modification of a sbom

### ISSUE THREAD

**Issue by CBeck-96** [Festo-se/cyclonedx-editor-validator#173]
Allow to use set or a similar command with subschemata and or regex additional to name+version+group. 
So all components that fullfill the provided schema get modified.
This operation would be more complex, but since it is planned as addition to the regular set schema, it would not be to the detriment of the already implemented function but a extension to be more versatile. 
With this, more complex operations would be possible, that can be necessary, depending on the output of the creation tool.

**Comment by italvi** [comment]
It would only add more complexity and add dangerous operations that could "destroy" your whole SBOM, if a wrong regex is provided. `set` is a safe choice here and with the newly introduced `version_range` (via #146) should already fulfill enough use-cases. If more users will require such a feature, we can re-open this issue, but up to now there is no real benefit.
