### ISSUE TITLE
Should `validate` print to stdout?

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#280]
Currently, the *validate* command prints all its messages to stderr. AFAIK, it never prints anything to stdout. From the perspective of a script author this is unnecessarily cumbersome.

I would argue that only failures in the validation algorithm (e.g., unable to read files, programming bug, whatever) should print messages to stderr. The *expected* command output should go to stdout as with all other commands, even if in this case the expected output potentially contains validation errors.
It goes without saying that this would be a breaking change, requiring changes to existing scripts which use the output.

What do you think @italvi @CBeck-96 ?

**Comment by italvi** [comment]
Funny to hear this suggestion from you, after you were the one [removing](#204) it 😆 I heard from some colleagues that they were using stdout to write the output just to a file, without requiring a specific `report-format`, i.e. warnings-ng/gitlab-cq.

So: I would agree on that change, it's odd/inconsistence that validate is the only command not writing to stdout.

**Comment by mmarseu** [comment]
Ha, not true! I only removed a useless command-line option and fixed the documentation. Previously, it falsely claimed that validate wrote to stdout but it never did. It uses the same logging infrastructure which all other commands use for their info messages (which rightly go to stderr). 
So, I stand by my PR and by this issue 😝 

That said, it's great that you agree, so I can get on it!
