### ISSUE TITLE
Remove existing tools when writing the SBOM

### ISSUE THREAD

**Issue by CBeck-96** [Festo-se/cyclonedx-editor-validator#334]
Currently the output function just adds the CycloneDX toool to other toolt that might already be present. 
Those other tools should be removed first, since the SBOM was created using this tool.

**Comment by mmarseu** [comment]
@italvi pointed me to this issue to ask my opinion. I'm always happy to give my opinion on anything, so here it comes 😉 

The CDX spec generally leaves many details open to interpretation. In this case, the spec v1.6 says about [`metadata.tools`](https://cyclonedx.org/docs/1.6/json/#metadata_tools): 

>The tool(s) used in the creation, enrichment, and validation of the BOM.

Personally, I don't understand this to mean that it's _only_ the tool which created the SBOM but any tools which took part in the process. I think this is also in line with the spirit of CycloneDX I've perceived in the development of the spec and in the official  communication in GitHub issues about the spec. Their philosophy seems to be to amass as much information about the product as possible. At no point have I read a comment that said "naww, we won't capture that kind of info, that would be too much", so I don't see them promoting the deletion of historic data from the SBOM. 

That said, there seems to be a bug you discovered which stems from the fact that `init-sbom` creates the tool entry in another way than the rest of the commands. The resulting object isn't recognized by the algorithm, so it will add another object for cdx-ev when modified by `amend`, `set` or whatever.
The solution here would be to improve the algorithm in `output.py`.

Another bug that @italvi pointed out is that `merge` doesn't merge the tools of its inputs. It probably should, at least according to my interpretation of `metadata.tools`.

**Comment by CBeck-96** [comment]
This should be closed together with #337

**Comment by italvi** [comment]
Will be fixed via #337
