### ISSUE TITLE
Duplicate entries created in `metadata.tools`

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#337]
_Issue brought up in https://github.com/Festo-se/cyclonedx-editor-validator/issues/334#issuecomment-2530723783_

The algorithm in `output.py#update_tools()` is a little too inflexible when it tries to determine whether cdx-ev is already part of the tools array. The simple object comparison it does fails on entries created by `init-sbom`, leading to duplicate entries being created for the same version of cdx-ev.

We can either improve the algorithm or change the entry created by `init-sbom`. Personally, I prefer the first option.

**Comment by CBeck-96** [comment]
@mmarseu do you intend to create a compare_tools method?
(I would than use it in merge for #336)

**Comment by mmarseu** [comment]
> @mmarseu do you intend to create a compare_tools method? (I would than use it in merge for #336)

The comparison is so simply that an additional function isn't necessary. Simply use the existing `ComponentIdentity` class to compare.
Tools as defined by the current spec are also components, so the mechanisms in `ComponentIdentity` work perfectly. The deprecated tools array used a different definition, which is close enough, IMO, to work without any changes.
