### ISSUE TITLE
Support creation of a NOTICE file

### ISSUE THREAD

**Issue by italvi** [Festo-se/cyclonedx-editor-validator#69]
https://infra.apache.org/licensing-howto.html

**Comment by mmarseu** [comment]
Technically speaking, how do you want to go about this?
The NOTICE file as defined by the Apache license is a file containing any number of special, legally required license terms for the product at hand or any of its components. It is decidedly **not** a list of third-party licenses used in a project, so I fail to understand how this tool could possibly be able to collect the required information to put into a NOTICE file.

I do see a use-case for creating a list of third-party licenses. This sort of thing is typically needed when distributing a product and the SBOM *should* give us all the required information.

**Comment by italvi** [comment]
@mmarseu would you agree on having a command `list` and then just a sub-command `licenses`, i.e. we would just speak of a list of licenses, which is inspired by the format of a `NOTICE` file?

**Comment by mmarseu** [comment]
> @mmarseu would you agree on having a command `list` and then just a sub-command `licenses`, i.e. we would just speak of a list of licenses, which is inspired by the format of a `NOTICE` file?

I think that sounds good. I'd love to see an additional option to select the format. Off the top of my head, I can imagine at least two use cases:
- The license list for attribution purposes, e.g. `THIRD-PARTY`, or `LICENSE`, or whatever - just not `NOTICE` for the reason mentioned above.
- A CSV format for license compliance analysis.
