### ISSUE TITLE
Generated filename is invalid if component has hashes

### ISSUE THREAD

**Issue by mmarseu** [Festo-se/cyclonedx-editor-validator#99]
Some of the commands generate a new filename for the SBOM when used with the `--output` option pointing to a folder.

This filename currently fails to validate if `metadata.component.hashes` exists and is not empty.

That's because the filename generation algorithm in `output.py` doesn't take hashes into consideration at all.

On the other hand, the validator requires a hash to be present if the metadata component has at least one hash.

I'd be willing to fix this if you let me know which of the two sides of the problem you'd like to change: Either the hashes are added to the filename generator, or the validator accepts filenames without hashes even if the metadata component has one.

**Comment by italvi** [comment]
For me the second proposition is preferred as we don't state in our [documentation](https://festo-se.github.io/cyclonedx-editor-validator/available_commands/#validation-of-file-name) that, if present, the hash is mandatory in the filename. I would appreciate it if you could implement the change.
